### ISSUE TITLE
Sam Checklist

### ISSUE THREAD

**Issue by samryan18** [ejonokuchi/practice#1]
# leetcode-solutions

Solutions to LeetCode Problems and common algorithm implementations for personal interview prep.

Credit to a user on [Blind](https://www.teamblind.com/post/New-Year-Gift---Curated-List-of-Top-75-LeetCode-Questions-to-Save-Your-Time-OaM1orEU) for the list.

---

Arrays:
- [x] 1. Two Sum (Easy) ([LINK](https://leetcode.com/problems/two-sum/))
- [x] 121. Best Time to Buy and Sell Stock (Easy) ([LINK](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/))
- [x] 217. Contains Duplicate (Easy) ([LINK](https://leetcode.com/problems/contains-duplicate/))
- [x] 238. Product of Array Except Self (Medium) ([LINK](https://leetcode.com/problems/product-of-array-except-self/))
    * TODO: can do better solution
- [x] 53. Maximum Subarray (Easy) ([LINK](https://leetcode.com/problems/maximum-subarray/))
- [x] 152. Maximum Product Subarray (Medium) ([LINK](https://leetcode.com/problems/maximum-product-subarray/))
- [ ] 153. Find Minimum in Rotated Sorted Array (Medium) ([LINK](https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/))
- [ ] 33. Search in Rotated Sorted Array (Medium) ([LINK](https://leetcode.com/problems/search-in-rotated-sorted-array/))
- [ ] 15. 3Sum (Medium) ([LINK](https://leetcode.com/problems/3sum/))
- [x] 11. Container With Most Water (Medium) ([LINK](https://leetcode.com/problems/container-with-most-water/))

Binary:
- [ ] 371. Sum of Two Integers (Medium) ([LINK](https://leetcode.com/problems/sum-of-two-integers/))
- [x] 191. Number of 1 Bits (Easy) ([LINK](https://leetcode.com/problems/number-of-1-bits/))
- [ ] 338. Counting Bits (Easy) ([LINK](https://leetcode.com/problems/counting-bits/))
- [ ] 268. Missing Number (Easy) ([LINK](https://leetcode.com/problems/missing-number/))
- [ ] 190. Reverse Bits (Easy) ([LINK](https://leetcode.com/problems/reverse-bits/))

Dynamic Programming:
- [x] 70. Climbing Stairs (Easy) ([LINK](https://leetcode.com/problems/climbing-stairs/))
- [ ] 322. Coin Change (Medium) ([LINK](https://leetcode.com/problems/coin-change/))
- [ ] 300. Longest Increasing Subsequence (Medium) ([LINK](https://leetcode.com/problems/longest-increasing-subsequence/))
- [ ] 1143. Longest Common Subsequence (Medium) ([LINK](https://leetcode.com/problems/longest-common-subsequence/))
- [ ] 139. Word Break (Medium) ([LINK](https://leetcode.com/problems/word-break/))
- [ ] 377. Combination Sum IV (Medium) ([LINK](https://leetcode.com/problems/combination-sum-iv/))
- [ ] 198. House Robber (Medium) ([LINK](https://leetcode.com/problems/house-robber/))
- [ ] 213. House Robber II (Medium) ([LINK](https://leetcode.com/problems/house-robber-ii/))
- [ ] 91. Decode Ways (Medium) ([LINK](https://leetcode.com/problems/decode-ways/))
- [ ] 62. Unique Paths (Medium) ([LINK](//leetcode.com/problems/unique-paths/))
- [ ] 55. Jump Game (Medium) ([LINK](https://leetcode.com/problems/jump-game/))

Graph:
- [ ] 133. Clone Graph (Medium) ([LINK](https://leetcode.com/problems/clone-graph/))
- [ ] 207. Course Schedule (Medium) ([LINK](https://leetcode.com/problems/course-schedule/))
- [ ] 417. Pacific Atlantic Water Flow (Medium) ([LINK](https://leetcode.com/problems/pacific-atlantic-water-flow/))
- [ ] 200. Number of Islands (Medium) ([LINK](https://leetcode.com/problems/number-of-islands/))
- [ ] 128. Longest Consecutive Sequence (Medium) ([LINK](https://leetcode.com/problems/longest-consecutive-sequence/))
- [ ] 269. Alien Dictionary - Premium (Hard) ([LINK](https://leetcode.com/problems/alien-dictionary/))
- [ ] 261. Graph Valid Tree - Premium (Medium) ([LINK](https://leetcode.com/problems/graph-valid-tree/))
- [ ] 323. Number of Connected Components in an Undirected Graph - Premium (Medium) ([LINK](https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/))

Interval:
- [ ] 57. Insert Interval (Medium) ([LINK](https://leetcode.com/problems/insert-interval/))
- [ ] 56. Merge Intervals (Medium) ([LINK](https://leetcode.com/problems/merge-intervals/))
- [ ] 435. Non-overlapping Intervals (Medium) ([LINK](https://leetcode.com/problems/non-overlapping-intervals/))
- [x] 252. Meeting Rooms - Premium (Easy) ([LINK](https://leetcode.com/problems/meeting-rooms/))
- [ ] 253. Meeting Rooms II - Premium (Medium) ([LINK](https://leetcode.com/problems/meeting-rooms-ii/))

Linked List:
- [x] 206. Reverse Linked List (Easy) ([LINK](https://leetcode.com/problems/reverse-linked-list/))
- [ ] 141. Linked List Cycle (Easy) ([LINK](https://leetcode.com/problems/linked-list-cycle/))
- [ ] 21. Merge Two Sorted Lists (Easy) ([LINK](https://leetcode.com/problems/merge-two-sorted-lists/))
- [ ] 23. Merge k Sorted Lists (Hard) ([LINK](https://leetcode.com/problems/merge-k-sorted-lists/))
- [ ] 19. Remove Nth Node From End of List (Medium) ([LINK](https://leetcode.com/problems/remove-nth-node-from-end-of-list/))
- [ ] 143. Reorder List (Medium) ([LINK](https://leetcode.com/problems/reorder-list/))

Matrix:
- [ ] 73. Set Matrix Zeroes (Medium) ([LINK](https://leetcode.com/problems/set-matrix-zeroes/))
- [ ] 54. Spiral Matrix (Medium) ([LINK](https://leetcode.com/problems/spiral-matrix/))
- [ ] 48. Rotate Image (Medium) ([LINK](https://leetcode.com/problems/rotate-image/))
- [ ] 79. Word Search (Medium) ([LINK](https://leetcode.com/problems/word-search/))

String:
- [ ] 3. Longest Substring Without Repeating Characters (Medium) ([LINK](https://leetcode.com/problems/longest-substring-without-repeating-characters/))
- [ ] 424. Longest Repeating Character Replacement (Medium) ([LINK](https://leetcode.com/problems/longest-repeating-character-replacement/))
- [ ] 76. Minimum Window Substring (Hard) ([LINK](https://leetcode.com/problems/minimum-window-substring/))
- [ ] 242. Valid Anagram (Easy) ([LINK](https://leetcode.com/problems/valid-anagram/))
- [ ] 49. Group Anagrams (Medium) ([LINK](https://leetcode.com/problems/group-anagrams/))
- [ ] 20. Valid Parentheses (Easy) ([LINK](https://leetcode.com/problems/valid-parentheses/))
- [ ] 125. Valid Palindrome (Easy) ([LINK](https://leetcode.com/problems/valid-palindrome/))
- [ ] 5. Longest Palindromic Substring (Medium) ([LINK](https://leetcode.com/problems/longest-palindromic-substring/))
- [ ] 647. Palindromic Substrings (Medium) ([LINK](https://leetcode.com/problems/palindromic-substrings/))
- [ ] 271. Encode and Decode Strings - Premium (Medium) ([LINK](https://leetcode.com/problems/encode-and-decode-strings/))

Tree:
- [ ] 104. Maximum Depth of Binary Tree (Easy) ([LINK](https://leetcode.com/problems/maximum-depth-of-binary-tree/))
- [ ] 100. Same Tree (Easy) ([LINK](https://leetcode.com/problems/same-tree/))
- [ ] 226. Invert Binary Tree (Easy) ([LINK](https://leetcode.com/problems/invert-binary-tree/))
- [ ] 124. Binary Tree Maximum Path Sum (Hard) ([LINK](https://leetcode.com/problems/binary-tree-maximum-path-sum/))
- [ ] 102. Binary Tree Level Order Traversal (Medium) ([LINK](https://leetcode.com/problems/binary-tree-level-order-traversal/))
- [ ] 297. Serialize and Deserialize Binary Tree (Hard) ([LINK](https://leetcode.com/problems/serialize-and-deserialize-binary-tree/))
- [ ] 572. Subtree of Another Tree (Easy) ([LINK](https://leetcode.com/problems/subtree-of-another-tree/))
- [ ] 105. Construct Binary Tree from Preorder and Inorder Traversal (Medium) ([LINK](https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/))
- [ ] 98. Validate Binary Search Tree (Medium) ([LINK](https://leetcode.com/problems/validate-binary-search-tree/))
- [ ] 230. Kth Smallest Element in a BST (Medium) ([LINK](https://leetcode.com/problems/kth-smallest-element-in-a-bst/))
- [ ] 235. Lowest Common Ancestor of a Binary Search Tree (Easy) ([LINK](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/))
- [ ] 208. Implement Trie (Prefix Tree (Medium) ([LINK](https://leetcode.com/problems/implement-trie-prefix-tree/))
- [ ] 211. Design Add and Search Words Data Structure (Medium) ([LINK](https://leetcode.com/problems/add-and-search-word-data-structure-design/))
- [ ] 212. Word Search II (Hard) ([LINK](https://leetcode.com/problems/word-search-ii/))

Heap:
- [ ] 347. Top K Frequent Elements (Medium) ([LINK](https://leetcode.com/problems/top-k-frequent-elements/))
- [ ] 295. Find Median from Data Stream (Hard) ([LINK](https://leetcode.com/problems/find-median-from-data-stream/))

Bonus:
- [ ] 741. Cherry Pickup (Hard) ([LINK](https://leetcode.com/problems/cherry-pickup/))

**Comment by ejonokuchi** [comment]
done

**Comment by ejonokuchi** [comment]
realized you're using this as a checklist

**Comment by ejonokuchi** [comment]
think we're good to close this :)
